config/routes.rb
Rails.application.routes.draw do

  root 'repos#index'

  scope ':repo', controller: 'repos', constraints: { repo: /[\w._-]+/ } do
    get 'commits/:ref', action: :commits, as: :repo_commits
    get 'commit/:oid', action: :commit, as: :repo_commit
    get 'blob/:ref/*path', action: :blob, as: :repo_blob, format: false
    get 'edit_file/:ref/*path', action: :edit_file, as: :repo_edit_file, format: false
    post 'update_file/:ref/*path', action: :update_file, as: :repo_update_file, format: false
    get 'tree/:ref/(*path)', action: :tree, as: :repo_tree
    get '', action: :tree, as: :repo
  end

end

app/models/repo.rb
# -*- coding: utf-8 -*-
class Repo
  MONITORED_DIR = File.join(Rails.root, 'repos')

  def initialize path
    @name = File.basename path, '.git'
    @repository = (Rugged::Repository.new(path) rescue nil)
  end

  attr_accessor :name, :repository

  def nil?
    @repository.nil?
  end

  class << self
    attr_reader :repos

    def [] name
      repos.detect {|repo| repo.name.downcase == name.downcase}
    end
  end

  def self.load_repos
    @repos = []
    FileUtils.mkdir_p MONITORED_DIR unless File.directory? MONITORED_DIR
    Dir.glob(File.join(MONITORED_DIR, '*')).each do |entry|
      repo = self.new(entry)
      @repos.push(repo) unless repo.nil?
    end
    @repos
  end
  self.load_repos

  def self.find_by_name name
    repos.detect {|repo| repo.name.downcase == name.strip.downcase}
  end

  def method_missing method, *args
    repository.send method, *args
  end

  def to_param
    name
  end
end

app/controllers/repos_controller.rb
# -*- coding: utf-8 -*-
class ReposController < ApplicationController
  skip_before_action :load_repo, only: [:index]
  before_action :load_ref, only: [:tree, :blob, :commits, :edit_file, :update_file]
  before_action :load_blob, only: [:blob, :edit_file, :update_file]

  def index
    @repos = Repo.repos
  end

  def tree
    root_tree = @branch.target.tree

    if params[:path].present?
      entry = (root_tree.path(params[:path]) rescue nil)
      @tree = entry && entry[:type].eql?(:tree) ? @repo.lookup(entry[:oid]) : root_tree
    else
      @tree =root_tree
    end
  end

  def blob
  end

  def edit_file
  end

  def update_file
    index = @repo.repository.index
    index.read_tree(@branch.target.tree)

    new_blob = @repo.write(params[:content].delete!("\r"), :blob)
    index.add({path: params[:path], oid: new_blob, mode: 0100644})
    new_tree = index.write_tree(@repo.repository)

    options = {tree: new_tree, message: params[:message]}
    current_user = {
      email: Rugged::Config.global['user.email'],
      name:  Rugged::Config.global['user.name'],
      time: Time.now
    }
    options[:author] = current_user
    options[:committer] = current_user
    options[:parents] = @repo.empty? ? [] : [ @branch.target ]
    options[:update_ref] = @branch.canonical_name

    Rugged::Commit.create(@repo.repository, options)

    redirect_to repo_blob_path(repo: params[:repo], ref: params[:ref], path: params[:path])
  end


  def commits
    @commits = []
    n = 0
    per_page = 35
    @finished = true
    params[:page] = (params[:page] || 1).to_i

    walker = Rugged::Walker.new(@repo.repository)
    walker.sorting(Rugged::SORT_DATE)
    walker.push @branch.target

    walker.each_with_index do |commit, index|
      next if index + 1 <= per_page * (params[:page] - 1)

      if n == per_page
        @finished = false
        break
      else
        @commits.push commit
        n += 1
      end

    end

    @commits = @commits.group_by do |commit|
      commit.time.strftime("%Y-%m-%d")
    end
  end

  def commit
    @commit = @repo.lookup params[:oid]

    if @commit.parents.empty?
      @diff = @commit.diff(reverse: true)
    else
      @diff = @commit.parents[0].diff(@commit)
    end
    @diff.find_similar!

    render stream: true
  end

private
  def load_ref
    params[:ref] ||= 'master'
    @branch = @repo.branches[params[:ref]]
  end

  def load_blob
    @blob = @repo.blob_at(@branch.target.oid, params[:path])
  end
end

app/helpers/repos_helper.rb
module ReposHelper
  def file_icon entry
    class_names = ['octicon']

    case entry[:type]
    when :blob
      class_names << 'octicon-file-text'
    when :tree
      class_names << 'octicon-file-directory'
    end

    content_tag :span, nil, class: class_names.join(' ')
  end

  def file_link entry
    path = case entry[:type]
      when :blob
        repo_blob_path(repo: params[:repo], ref: params[:ref], path: [params[:path], entry[:name]].compact.join('/'))
      when :tree
        repo_tree_path(repo: params[:repo], ref: params[:ref], path: [params[:path], entry[:name]].compact.join('/'))
    end
    link_to entry[:name], path
  end

  def render_path_breadcumb
    paths = (params[:path] || '').split('/')
    final_path = paths.pop

    links = []

    repo_name = content_tag :span, class: 'repo-root' do
      link_to params[:repo], repo_tree_path(repo: params[:repo], ref: params[:ref])
    end

    links.push repo_name

    paths.each_with_index do |path, index|
      path_link = content_tag :span do
        link_to path, repo_tree_path(repo: params[:repo], ref: params[:ref], path: paths.take(index + 1) )
      end
      links.push path_link
    end

    if final_path
      links.push(content_tag(:strong, final_path, class: 'final-path'))
    end
    links.join("<span class='separator'>/</span>").html_safe
  end

  def abbrev_sha shas, &block
    abbreviated_shas = []
    Rugged.minimize_oid(shas) do |oid|
      abbreviated_shas.push oid
    end

    abbreviated_shas.zip(shas).each do |short, oid|
      yield short, oid
    end
  end

  def lexer_for_delta delta
    new_path, old_path = delta.new_file[:path], delta.old_file[:path]

    path = case delta.status
    when :modified, :added, :typechange, :renamed, :copied
      new_path
    when :deleted, :ignored, :untracked
      old_path
    end

    language = Linguist.new(path).language.ace_mode

    Pygments::Lexer.find(language) ? language : nil
  end

  def format_filename delta
    new_path, old_path = delta.new_file[:path], delta.old_file[:path]

    case delta.status
    when :modified, :added, :typechange
      new_path
    when :deleted, :ignored, :untracked
      old_path
    when :renamed
      abbr_path_change(old_path, new_path, " &rarr; ")
    when :copied
      abbr_path_change(old_path, new_path, " &rArr; ")
    end
  end

  def highlight_code code, language
    options = {:nowrap => 'False', linenos: 'table'}
    if Pygments::Lexer.find(language)
      Pygments.highlight(code, :lexer => language, options: options)
    else
      Pygments.highlight(code, :lexer => "text", options: options)
    end
  end

  def highlight_diff code, lexer
    if lexer
      Pygments.highlight(code, :lexer => lexer, options: {nowrap: 'True'}).try(:html_safe) || code
    else
      code
    end
  end

private
  def abbr_path_change old_path, new_path, separator = " &rarr; "
    old_path_segments = old_path.split('/')
    new_path_segments = new_path.split('/')

    uncommonIdx = old_path_segments.zip(new_path_segments).index {|old, new| old != new } || 0

    if uncommonIdx == 0
      [old_path, new_path].join(separator).html_safe
    else
      path_change = [old_path_segments.drop(uncommonIdx).join('/'), new_path_segments.drop(uncommonIdx).join('/')].join(separator)
      [old_path_segments.take(uncommonIdx).join('/'), "{#{path_change}}"].join('/').html_safe
    end
  end
end

app/views/repos/_branch_switcher.html.haml
.select-menu.left
  %span.minibutton.select-menu-button.css-truncate
    %span.octicon.octicon-git-branch
    %span.css-truncate-target= params[:ref]
  .select-menu-modal-holder
    .select-menu-modal
      .select-menu-header
        %span.select-menu-title Select Branch
        %span.octicon.octicon-x.select-menu-close
      .select-menu-list.selected
        - @repo.branches.each do |branch|
          .select-menu-item{class: branch.name.eql?(params[:ref]) ? 'selected' : ''}
            %span.select-menu-item-icon.octicon.octicon-check
            = link_to branch.name, url_for(controller: params[:controller], action: params[:action], repo: params[:repo], ref: branch.name, path: params[:path]), class: 'select-menu-item-text css-truncate-target'
  :javascript
    $(function(){
      $(".select-menu-button").click(function(){
        $(this).parent('.select-menu').toggleClass('active');
      });
      $(".select-menu-item").mouseover(function(){
        $(".select-menu-item").removeClass('navigation-focus');
        $(this).addClass('navigation-focus');
      });
      $(".select-menu-close, body").click(function(){
        $(".select-menu").removeClass('active');
      });
      $(".select-menu").click(function(event){
        event.stopPropagation();
      })
    });

app/views/repos/_branch_switcher.html.slim
.select-menu.left
  span.minibutton.select-menu-button.css-truncate
    span.octicon.octicon-git-branch
    span.css-truncate-target=< params[:ref]
  .select-menu-modal-holder
    .select-menu-modal
      .select-menu-header
        span.select-menu-title Select Branch
        span.octicon.octicon-x.select-menu-close
      .select-menu-list.selected
        - @repo.branches.each do |branch|
          .select-menu-item class= (branch.name.eql?(params[:ref]) ? 'selected' : '')
            span.select-menu-item-icon.octicon.octicon-check
            = link_to branch.name, url_for(controller: params[:controller], action: params[:action], repo: params[:repo], ref: branch.name, path: params[:path]), class: 'select-menu-item-text css-truncate-target'
  javascript:
    $(function(){
      $(".select-menu-button").click(function(){
        $(this).parent('.select-menu').toggleClass('active');
      });
      $(".select-menu-item").mouseover(function(){
        $(".select-menu-item").removeClass('navigation-focus');
        $(this).addClass('navigation-focus');
      });
      $(".select-menu-close, body").click(function(){
        $(".select-menu").removeClass('active');
      });
      $(".select-menu").click(function(event){
        event.stopPropagation();
      })
    });

app/views/repos/_file_nav.html.haml
.file-navigation.in-mid-page
  = link_to repo_commits_path(repo: @repo.name, ref: @branch.name), class: 'right' do
    .octicon.octicon-history
    Commits
  = render 'branch_switcher'
  .breadcrumb
    = render_path_breadcumb

app/views/repos/_file_nav.html.slim
.file-navigation.in-mid-page
  = link_to repo_commits_path(repo: @repo.name, ref: @branch.name), class: 'right' do
    .octicon.octicon-history
    |  Commits
  = render 'branch_switcher'
  .breadcrumb
    = render_path_breadcumb

app/views/repos/_file_patch.html.slim
- delta = patch.delta
- lexer = lexer_for_delta(delta)
.file id="diff-#{index}"
  .meta
    .info
      span= format_filename(delta)
  - if patch.changes == 0
    .data.highlight.empty
      - if delta.binary?
        | Binary file not shown
      - elsif delta.renamed?
        | File renamed without changes
  - else
    - if index > 250
      .data.highlight.empty
        | Sorry, we could not display the changes to this file because there were too many other changes to display.
    - else
      .data.highlight.blob-wrapper
        table.diff-table
          tbody
            - patch.each_hunk do |hunk|
              tr
                td.blob-num ...
                td.blob-num ...
                td.blob-code.blob-code-hunk
                  | @@ -#{hunk.old_start},#{hunk.old_lines} +#{hunk.new_start},#{hunk.new_lines}
              - hunk.each_line do |line|
                - next if line.eof_newline_added? or line.eof_newline_removed? or line.eof_no_newline?
                - type = line.addition? ? 'addition' : (line.deletion? ? 'deletion' : '')
                - indicator = line.addition? ? "+" : (line.deletion? ? '-' : ' ')
                tr
                  td.blob-num class=(type.blank? ? '' : 'blob-num-' + type) data-line-number=(line.old_lineno > 0 ? line.old_lineno : nil)
                  td.blob-num class=(type.blank? ? '' : 'blob-num-' + type) data-line-number=(line.new_lineno > 0 ? line.new_lineno : nil)
                  td.blob-code class=(type.blank? ? '' : 'blob-code-' + type)
                    = indicator
                    / = line.content.force_encoding("UTF-8")
                    = highlight_diff(line.content.force_encoding("UTF-8"), lexer)

app/views/repos/blob.html.slim
= render 'file_nav'

.file-box
  .file
    .meta.clearfix
      .info.file-name
        span= File.basename(params[:path])
        span.meta-divider
        span= number_to_human_size @blob.size
      .actions
        = link_to repo_edit_file_path(repo: params[:repo], ref: params[:ref], path: params[:path]),  class: 'octicon-button' do
          span.octicon.octicon-pencil
    .blob-wrapper.data class="type-#{Linguist.new(params[:path]).language.ace_mode}"
      - if @blob.binary?
        p Binary file not shown
      - else
        = highlight_code(@blob.text.force_encoding("UTF-8"), Linguist.new(params[:path]).language.ace_mode).html_safe

app/views/repos/commit.html.slim
- title "#{@commit.message} · #{@commit.oid.slice(0..6)}"

.commit.full-commit
  p.commit-title
    = @commit.message
  .commit-meta.clearfix
    .sha-block
      | commit
      span.sha=< @commit.oid
    .sha-block
      => pluralize(@commit.parents.size, 'parent')
      - abbrev_sha(@commit.parent_ids) do |short, oid|
        => link_to short, repo_commit_path(repo: params[:repo], oid: oid)
    .authorship
      span.author-name=> @commit.author[:name]
      | authored on
      = @commit.author[:time].strftime("%Y-%m-%d %H:%M")

#toc.details-collapse.table-of-contents.open
  .toc-diff-stats
    span.octicon.octicon-diff
    | Showing #{@diff.stat[0]} changed #{'file'.pluralize(@diff.stat[0])} with
    strong
      =>< number_with_delimiter(@diff.stat[1])
      =<> 'addition'.pluralize(@diff.stat[1])
    | and
    strong
      =<> number_with_delimiter(@diff.stat[2])
      => 'addition'.pluralize(@diff.stat[2])
  ol.content.collapse
    - @diff.each_patch.with_index do |patch, index|
      - delta = patch.delta
      li
        span.diffstat
          span.lines-added
            span.diffstat-icon +
            = patch.stat[0]
          span.lines-deleted
            span.diffstat-icon -
            = patch.stat[1]

        => content_tag :span, nil, class: 'octicon octicon-diff-' + delta.status.to_s, title: delta.status.to_s
        = link_to format_filename(delta), "#diff-#{index}"
#files.file-box.diff-view
  - @diff.each_patch.with_index do |patch, index|
    = render partial: 'file_patch', locals: {patch: patch, index: index}

app/views/repos/commits.html.haml
.file-navigation
  = render 'branch_switcher'

.commits-listing.commits-listing-padded
  - @commits.each do |day, commits|
    .commit-group-title
      %span.octicon.octicon-git-commit
      Commits on #{day}
    %ol.commit-group.table-list.table-list-bordered
      - commits.each do |commit|
        %li.commit.commits-list-item.table-list-item
          .table-list-cell{style: 'width:120px;color:#333;font-size:13px;'}
            = commit.committer[:name]
          .table-list-cell
            %p.commit-title
              = link_to commit.message, repo_commit_path(oid: commit.oid)
.paginate-container
  .pagination
    - if params[:page] > 1
      = link_to 'Newer', repo_commits_path(repo: params[:repo], ref: params[:ref], page: params[:page] - 1)
    - else
      %span.disabled Newer
    - if @finished
      %span.disabled Older
    - else
      = link_to 'Older', repo_commits_path(repo: params[:repo], ref: params[:ref], page: params[:page] + 1)

app/views/repos/commits.html.slim
.file-navigation
  = render 'branch_switcher'

.commits-listing.commits-listing-padded
  - @commits.each do |day, commits|
    .commit-group-title
      span.octicon.octicon-git-commit
      | Commits on #{day}
    ol.commit-group.table-list.table-list-bordered
      - commits.each do |commit|
        li.commit.commits-list-item.table-list-item
          .table-list-cell style='width:120px;color:#333;font-size:13px;'
            = commit.committer[:name]
          .table-list-cell
            p.commit-title
              = link_to commit.message, repo_commit_path(oid: commit.oid)
.paginate-container
  .pagination
    - if params[:page] > 1
      = link_to 'Newer', repo_commits_path(repo: params[:repo], ref: params[:ref], page: params[:page] - 1)
    - else
      span.disabled Newer
    - if @finished
      span.disabled Older
    - else
      = link_to 'Older', repo_commits_path(repo: params[:repo], ref: params[:ref], page: params[:page] + 1)

app/views/repos/edit_file.html.haml
.file-box.edit-file
  .breadcrumb
    Editing
    = render_path_breadcumb
  = form_tag repo_update_file_path(repo: params[:repo], ref: params[:ref], path: params[:path]), class: 'edit-blob-form js-blob-form' do
    .file.js-code-editor.container-preview.show-code
      .commit-create
        = text_area_tag :content, @blob.content.force_encoding('UTF-8'), id: 'blob_contents', class: 'file-editor-textarea js-blob-contents js-code-textarea', autofocus: true, rows: 35
    .commit-message-box
      %h3.file-commit-form-heading Commit changes
      = text_area_tag :message, nil, class: 'input-block input-contrast', placeholder: "Update #{File.basename(params[:path])}", rows: 2
    = submit_tag 'Commit Changes', class: 'button primary js-blob-submit', disabled: true, id: 'submit-btn'
    = link_to 'Cancel', repo_blob_path(repo: params[:repo], ref: params[:ref], path: params[:path]), class: 'button danger cancel'

= javascript_include_tag 'ace-min/ace.js', 'data-turbolinks-track' => false

:javascript
  var bla;
  $(function(){
    var textArea = $("#blob_contents").hide(),
        originalContent = textArea.val(),
        editorContainer = $('<div class="ace-github-light"></div>').insertAfter(textArea).css({width: '100%', height: '500px'}),
        commitForm = $('form.edit-blob-form'),
        submitBtn = $('#submit-btn', commitForm),
        messageBox = $("#message", commitForm);
      // setup ace eidtor
      var editor = ace.edit(editorContainer[0]);
      bla = editor;
      editor.$blockScrolling = Infinity;
      editor.setTheme("ace/theme/github");
      editor.getSession().setMode("ace/mode/#{Linguist.new(params[:path]).language.ace_mode}");
      editor.getSession().setValue(originalContent);
      // 更新提交按钮状态
      editor.on('change',function(){
        if (editor.getSession().getValue() == originalContent){
          submitBtn.attr("disabled", true);
        } else {
          submitBtn.attr("disabled", false);
        }
      });

      commitForm.submit(function(){
        textArea.val(editor.getSession().getValue());
        var message = messageBox.val();
        if ($.trim(message) === ''){
          messageBox.val(messageBox.attr('placeholder'));
        }
      });
  });

app/views/repos/edit_file.html.slim
.file-box.edit-file
  .breadcrumb
    | Editing
    =< render_path_breadcumb
  = form_tag repo_update_file_path(repo: params[:repo], ref: params[:ref], path: params[:path]), class: 'edit-blob-form js-blob-form' do
    .file.js-code-editor.container-preview.show-code
      .commit-create
        = text_area_tag :content, @blob.content.force_encoding('UTF-8'), id: 'blob_contents', class: 'file-editor-textarea js-blob-contents js-code-textarea', autofocus: true, rows: 35
    .commit-message-box
      h3.file-commit-form-heading Commit changes
      = text_area_tag :message, nil, class: 'input-block input-contrast', placeholder: "Update #{File.basename(params[:path])}", rows: 2
    = submit_tag 'Commit Changes', class: 'button primary js-blob-submit', disabled: true, id: 'submit-btn'
    =< link_to 'Cancel', repo_blob_path(repo: params[:repo], ref: params[:ref], path: params[:path]), class: 'button danger cancel'

= javascript_include_tag 'ace-min/ace.js', 'data-turbolinks-track' => false

javascript:
  var bla;
  $(function(){
    var textArea = $("#blob_contents").hide(),
        originalContent = textArea.val(),
        editorContainer = $('<div class="ace-github-light"></div>').insertAfter(textArea).css({width: '100%', height: '500px'}),
        commitForm = $('form.edit-blob-form'),
        submitBtn = $('#submit-btn', commitForm),
        messageBox = $("#message", commitForm);
      // setup ace eidtor
      var editor = ace.edit(editorContainer[0]);
      bla = editor;
      editor.$blockScrolling = Infinity;
      editor.setTheme("ace/theme/github");
      editor.getSession().setMode("ace/mode/#{Linguist.new(params[:path]).language.ace_mode}");
      editor.getSession().setValue(originalContent);
      //更新提交按钮状态
      editor.on('change',function(){
        if (editor.getSession().getValue() == originalContent){
          submitBtn.attr("disabled", true);
        } else {
          submitBtn.attr("disabled", false);
        }
      });

      commitForm.submit(function(){
        textArea.val(editor.getSession().getValue());
        var message = messageBox.val();
        if ($.trim(message) === ''){
          messageBox.val(messageBox.attr('placeholder'));
        }
      });
  });

app/views/repos/index.html.slim
ul.repo-list
  - @repos.each do |repo|
    li.repo-list-item
      .repo-list-stats
        span.repo-list-stat-item
          i.octicon.octicon-git-branch
          =< repo.branches.count
      h3.repo-list-name
        = link_to repo.name, repo_path(repo: repo.name)

app/views/repos/tree.html.haml
= render 'file_nav'

.commit.commit-tease.js-details-container
  %p.commit-title
    = link_to @branch.target.message, repo_commit_path(repo: params[:repo], oid: @branch.target.oid)
.file-wrap
  %table.files
    %tbody
      - @tree.each do |entry|
        %tr
          %td.icon
            = file_icon entry
          %td.content
            %span.css-truncate.css-truncate-target
              = file_link entry
          %td.message
          %td.age

app/views/repos/tree.html.slim
= render 'file_nav'

.commit.commit-tease.js-details-container
  p.commit-title
    = link_to @branch.target.message, repo_commit_path(repo: params[:repo], oid: @branch.target.oid)
.file-wrap
  table.files
    tbody
      - @tree.each do |entry|
        tr
          td.icon
            = file_icon entry
          td.content
            span.css-truncate.css-truncate-target
              = file_link entry
          td.message
          td.age